name: Spring Boot CI/CD Pipeline

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

env:
  JAR_FILE: ${{ secrets.JAR_FILE }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Run Tests
      run: ./gradlew test

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Package
        path: build/libs

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/develop'

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: Package
        path: build/libs

    - name: Add SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: ${{ secrets.EC2_HOST }}

    - name: Deploy to EC2
      run: |
        if [ ! -f build/libs/${{ secrets.JAR_FILE }} ]; then
          echo "JAR file not found"
          exit 1
        fi
        scp -o StrictHostKeyChecking=no build/libs/${{ secrets.JAR_FILE }} ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:${{ secrets.DEPLOY_DIR }}/
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF
          cd ${{ secrets.DEPLOY_DIR }}
          pkill -f ${{ secrets.JAR_FILE }} || true
          nohup java -jar ${{ secrets.JAR_FILE }} > /dev/null 2>&1 &
        EOF
